### ISSUE TITLE
Vocabularies

### ISSUE THREAD

**Issue by paulduchesne** [FIAF/modelling-workshops#9]
@torbjornbp @natashafairbairn @circesanchez @annahoegner @Rose-EFG @stephenmcconnachie @ladislav-nfa as we are now at the halfway mark of the workshop series, and making good progress on the ontology structure, I thought it could be a good moment to look at available vocabularies to incorporate into this project.

Below are a list of defined classes, and notes on where vocabularies are available, preferencing those which can be found in the Cataloguing Manual. I might begin adding these in directly and look forward to any discussion on which you think correspond with vocabularies used by institutions and which do not.

~

*Work/Variant* - actioned [here](https://github.com/FIAF/modelling-workshops/blob/main/classes/fiafcore-workvariant.ttl).
Both manual and EN15907 agree on a vocabulary of four values (Analytic, Collection, Monographic, Serial) which @natashafairbairn was keen to retain here.

*Activity* - actioned [here](https://github.com/FIAF/modelling-workshops/blob/main/classes/fiafcore-activity.ttl).
The FIAF Glossary of Filmographic Terms contains a rich, multi-tier and multilingual vocabulary of terms (mostly under section "B").

*Agent* - actioned [here](https://github.com/FIAF/modelling-workshops/blob/main/classes/fiafcore-agent.ttl).
The manual (1.4.1) lists a vocabulary of "Person", "Corporate Body", "Family" and "Person Group", but I wonder if this could be simplified to simply "Person" and "Organisation" as I have seen elsewhere? Although "Person Group" does address an ongoing problem where persons are credited in combination (eg "Coen Brothers", "The Wachowskis") and are not really a "person" nor an "organisation".

*Country* - actioned [here](https://github.com/FIAF/modelling-workshops/blob/main/classes/fiafcore-country.ttl).
The obvious resource here is ISO-3166.

*Event* - actioned [here](https://github.com/FIAF/modelling-workshops/blob/main/classes/fiafcore-event.ttl).
The manual (D.4) lists "Publication", "Award/Nomination", "Production", "Rights/Copyright/Registration", "Preservation", "Decision", "Manufacture", "Inspection" and "Acquisition". Each of these contain their own subclasses - my question here would be how these have been adopted by institutions, and whether we should support just the top level or the whole tree.

*Form* - actioned [here](https://github.com/FIAF/modelling-workshops/blob/main/classes/fiafcore-form.ttl).
FIAF Glossary of Filmographic Terms contains a list of "Forms" under section "D".

*Genre*
No obvious resources come to mind, would be interesting to dedicate an upcoming talk to compare vocabularies between our institutions and see if there is convergence (or not!).

*Identifier* - actioned [here](https://github.com/FIAF/modelling-workshops/blob/main/classes/fiafcore-identifier.ttl).
The manual (1.3.1) lists ISAN, EIDR and VIAF. I would support adding Wikidata. There should also be support for internal identifiers here (eg BFI, NFA etc), but a technical question, how should these be modeled? It seems tedious to create "identifier" subclasses for each institutions. One approach is do more work on proper data provenance peer statement, and then just use an "internal identifier" class which can be used in combination with provenance data to derive source of identifier.

*Subject*
As a "subject" can be (to my understanding) virtually anything, hard to imagine a comprehensive vocabulary. Maybe the property can be kept open for any resource (eg Wikidata, LoC, etc).

*Title* - actioned [here](https://github.com/FIAF/modelling-workshops/blob/main/classes/fiafcore-title.ttl).
The manual (A.2) lists "Alternative Title", "Identifying Title", "Other Title Information", "Preferred Title", "Supplied/Devised Title", "Title Proper". The manual also contains nine additional subclasses of "Alternative Title" (A.2.4.1). As with Event, is it useful to include the full set at this stage or just the top level?

*Variant Type* - actioned [here](https://github.com/FIAF/modelling-workshops/blob/main/classes/fiafcore-varianttype.ttl).
The manual (D.2) contains the following vocabulary: "Censored", "Dubbed", "Subtitled", "Abridged/Condensed", "Augmented", "Preservation/Restoration"
"Different sound track", "Sonorized", "Colourized", "Black and white copy of work originally issued in colour".

~

*Manifestation* - actioned [here](https://github.com/FIAF/modelling-workshops/blob/main/classes/fiafcore-manifestation.ttl).
The manual (D.5) contains a vocabulary: "Pre-Release", "Theatrical Distribution", "Non-Theatrical Distribution", "Not For Release", "Unreleased", "Home Viewing Publication", "Broadcast", "Internet", "Preservation/Restoration", "Unknown Manifestation".

*Colour Characteristic* - actioned [here](https://github.com/FIAF/modelling-workshops/blob/main/classes/fiafcore-colourcharacteristic.ttl) and [here](https://github.com/FIAF/modelling-workshops/blob/main/classes/fiafcore-colourstandard.ttl).
The manual (D.7.11) contains a vocabulary: "Colour", "Colour + Black & White", "Tinted", "Black and white", "Black and white (tinted)", "Black and white (toned)", "Black and white (tinted and toned)", "Sepia". My understanding is that the Colour Characteristic then has a "Has Colour Standard" property for technical specifics of the colour standards used, which has a vocabulary under D.7.12: "Pathécolor", "Technicolor", "Kinemacolor", "Anscocolor", "Ferraniacolor", "Fujicolor", "Kodachrome", "Eastmancolor", "RGB", "YUV".

*Extent* - actioned [here](https://github.com/FIAF/modelling-workshops/blob/main/classes/fiafcore-extent.ttl).
The manual contains a vocabulary of Unit Types (D.7.6): "Reel", "Roll", "Cassette", "Cartridge", "Loop", "Disc", "File", "Digital tape". The manual 2.3.5.2 also recommends including "metres" and "feet", and digital measures like "MB", "GB" and "TB". 2.3.5.3 recommends the inclusion of duration, so "seconds", "minutes", "hours".

*Format* - actioned [here](https://github.com/FIAF/modelling-workshops/blob/main/classes/fiafcore-format.ttl).
The manual (D.7.2) contains a table of "specific carrier types" which could be nested under the "general carrier types" to serve as format vocabulary. This is clearly an incomplete list, but could serve as a good starting point.

*Image Characteristic* - actioned [here](https://github.com/FIAF/modelling-workshops/blob/main/classes/fiafcore-imagecharacteristic.ttl).
The manual includes two vocabularies for Aspect Ratio (D.7.14) and Aperture Format (D.7.15). Aspect Ratios listed are: "2.34:1", "2.39:1", "2.52:1", "2.7:1", "4:3". I am wondering if the FIAF Projection Manual has a glossary which could also be used in this context? I feel like the Aperture vocabulary could be assessed critically as I feel it is maybe grouping a few different attributes together which are not siblings.

*Language* - actioned [here](https://github.com/FIAF/modelling-workshops/blob/main/classes/fiafcore-language.ttl).
The obvious resource here is ISO-639.

*Language Usage* - actioned [here](https://github.com/FIAF/modelling-workshops/blob/main/classes/fiafcore-languageusage.ttl).
The manual (D.6) contains a vocabulary: "Dialogue language(s)", "Written languages", "Language(s) of summaries on containers", "Language(s) of accompanying material". Both "Dialogue" and "Written" have more granular entities.

*Sound Characteristic* - actioned [here](https://github.com/FIAF/modelling-workshops/blob/main/classes/fiafcore-soundcharacteristic.ttl), [here](https://github.com/FIAF/modelling-workshops/blob/main/classes/fiafcore-soundfixation.ttl) and [here](https://github.com/FIAF/modelling-workshops/blob/main/classes/fiafcore-soundsystem.ttl) .
The manual (D.7.4) contains a vocabulary of sound types: "Sound", "Silent", "Mute", "Combined", "Combined as Mute", "Combined as Sound", "Mixed", "Temporary". It would be good to have clarification of the definition of some of these terms (eg "combined" as in "combined with image"?). Once the general nature of the sound has been declared there are additional properties for "Sound Configuration" (manual 3.1.5.4 suggests "mono" and "stereo") and "Sound system" which has a vocabulary under D.7.13: "Dolby SR", "Dolby Digital", "Mute", "Combined Magnetic Sound", "Combined Optical Sound", "VA RCA Duplex". There is also a vocabulary for "Sound Fixation" at D.7.5: "Needle sound", "Optical", "Magnetic", "Analogue sound", "Digital".

~

*Item*
As discussed in the Item discussion I was in favour of adopting D.7.8 from the manual as the item vocabulary: "Colour Positive", "Colour Negative", "Copper Toned Positive", "Cyan Matrix", "Direct BW Positive", "Original negative", "Duplicate negative", "Positive","Original positive (reversal film)", "Duplicate positive", "Lavender", "Image negative", "Sound negative", "DCP". However much of this is very film-specific, so it would possibly be better expressed as a separate property with "general carrier type" acting as "item type": "Film", "Video Tape", "Video Disc", "Digital Tape", "Digital Disc", "Digital File".

*Base* - actioned [here](https://github.com/FIAF/modelling-workshops/blob/main/classes/fiafcore-base.ttl).
The manual (D.7.7) contains a vocabulary of bases: "Acetate", "Acrylic", "CTA", "Diacetate", "Mainly safety", "Mainly nitrate", "Mixed", "Mylar", "Nitrate", "Polyester", "PVC", "Safety", "Video", "Vinyl".

*Broadcast Standard* - actioned [here](https://github.com/FIAF/modelling-workshops/blob/main/classes/fiafcore-broadcaststandard.ttl).
The manual (3.1.5.10) contains a vocabulary: "NTSC", "PAL", "SECAM".

*Institution* - actioned [here](https://github.com/FIAF/modelling-workshops/blob/main/classes/fiafcore-agent.ttl).
A good suggestion from @Rose-EFG is that there should be no "institution" class, instead institutions should be organisation "agents". FIAF itself holds a good vocabulary of member institutions.

*Line Standard* - actioned [here](https://github.com/FIAF/modelling-workshops/blob/main/classes/fiafcore-linestandard.ttl).
The manual (D.7.21) contains a vocabulary: "405", "525", "625", "720", "1080"

*Resolution* - actioned [here](https://github.com/FIAF/modelling-workshops/blob/main/classes/fiafcore-resolution.ttl).
The manual (D.7.19) contains a vocabulary: "Standard Definition", "High Definition", "2k", "4k", "6k", "8k".

*Source Device* - actioned [here](https://github.com/FIAF/modelling-workshops/blob/main/classes/fiafcore-sourcedevice.ttl).
The manual (D.7.20) contains a vocabulary: "DVSI", "VT20", "HDCAM SRW5500/2"

*Source Software* - actioned [here](https://github.com/FIAF/modelling-workshops/blob/main/classes/fiafcore-sourcesoftware.ttl).
No vocabulary in the manual, I would suggest "FFmpeg" and other transcoder/editors as a good start. 

*Status* - actioned [here](https://github.com/FIAF/modelling-workshops/blob/main/classes/fiafcore-status.ttl).
The manual (D.7.3) contains a vocabulary: "Master", "Viewing", "Accessioned", "On Loan", "Status pending", "Removed".

*Stock* - actioned [here](https://github.com/FIAF/modelling-workshops/blob/main/classes/fiafcore-stock.ttl).
The manual (D.7.16) contains an extensive vocabulary. As there is a lot of overlap between manufacturers (eg Fuji produced film and videotape, 3M video and audiotape) I would question whether these should be nested or flat. An additional property should be Stock Batch (or maybe "stock value", "stock specific"?) which contains a string of the exact stock (eg "Panchromatic Separation Film 2238"). 

*Stream* - actioned [here](https://github.com/FIAF/modelling-workshops/blob/main/classes/fiafcore-stream.ttl), [here](https://github.com/FIAF/modelling-workshops/blob/main/classes/fiafcore-bitdepth.ttl) and [here](https://github.com/FIAF/modelling-workshops/blob/main/classes/fiafcore-codec.ttl) .
This is the biggest diversion from the manual, and I would propose that a stream can be of type "Audio Stream", "Video Stream", "Subtitle Stream" (or "track"?). Additional properties are "Has Codec", which has vocabularies under D.7.10 in the manual which clearly need expansion. Also "Has Bit Depth", with a vocabulary present at D.7.17 of the manual.

~ 

*Carrier*
No vocabularies expressed.

**Comment by natashafairbairn** [comment]
Hi Paul,

Have put a few points in reply in body of your email below.

Hope to see everyone later on at the workshop meeting today.

Best,
Natasha

From: Paul Duchesne ***@***.***>
Sent: 14 February 2023 19:47
To: FIAF/modelling-workshops ***@***.***>
Cc: Natasha Fairbairn ***@***.***>; Mention ***@***.***>
Subject: [FIAF/modelling-workshops] Vocabularies (Issue #9)

Attention. This email originated outside the BFI. Please be extra vigilant when opening attachments or clicking links.

@torbjornbp<https://url6.mailanyone.net/scanner?m=1pS1Gy-0000QT-4V&d=4%7Cmail%2F90%2F1676403600%2F1pS1Gy-0000QT-4V%7Cin6j%7C57e1b682%7C10717690%7C7962607%7C63EBE5506E134A1E3DA9F7CE5F804736&o=%2Fphti%3A%2Fgtsmbthtco%2Fu.pbnrojbro&s=eVAc0eH4lMGnPFKDG0JWMQU9Jds> @natashafairbairn<https://url6.mailanyone.net/scanner?m=1pS1Gy-0000QT-4V&d=4%7Cmail%2F90%2F1676403600%2F1pS1Gy-0000QT-4V%7Cin6j%7C57e1b682%7C10717690%7C7962607%7C63EBE5506E134A1E3DA9F7CE5F804736&o=%2Fphti%3A%2Fgtsmbthnco%2Fu.asatrafiahnriab&s=XSP4PTuq3-QulisZv3PtQoghKro> @circesanchez<https://url6.mailanyone.net/scanner?m=1pS1Gy-0000QT-4V&d=4%7Cmail%2F90%2F1676403600%2F1pS1Gy-0000QT-4V%7Cin6j%7C57e1b682%7C10717690%7C7962607%7C63EBE5506E134A1E3DA9F7CE5F804736&o=%2Fphti%3A%2Fgtsmbthcco%2Fu.ceireanhcsz&s=Wyf5-1UVZ3lvd32tOme1asGSc3Y> @annahoegner<https://url6.mailanyone.net/scanner?m=1pS1Gy-0000QT-4V&d=4%7Cmail%2F90%2F1676403600%2F1pS1Gy-0000QT-4V%7Cin6j%7C57e1b682%7C10717690%7C7962607%7C63EBE5506E134A1E3DA9F7CE5F804736&o=%2Fphti%3A%2Fgtsmbthaco%2Fu.nhnnregeao&s=kAIKp3pfUbTCEJ43KX8bABd81kw> @Rose-EFG<https://url6.mailanyone.net/scanner?m=1pS1Gy-0000QT-4V&d=4%7Cmail%2F90%2F1676403600%2F1pS1Gy-0000QT-4V%7Cin6j%7C57e1b682%7C10717690%7C7962607%7C63EBE5506E134A1E3DA9F7CE5F804736&o=%2Fphti%3A%2FgtsmbthRco%2Fu.GFE-eso&s=F95t5J6V6joczeo4xowp1RrjBFg> @stephenmcconnachie<https://url6.mailanyone.net/scanner?m=1pS1Gy-0000QT-4V&d=4%7Cmail%2F90%2F1676403600%2F1pS1Gy-0000QT-4V%7Cin6j%7C57e1b682%7C10717690%7C7962607%7C63EBE5506E134A1E3DA9F7CE5F804736&o=%2Fphti%3A%2Fgtsmbthsco%2Fu.chteonmcpeeihcann&s=COiLpshWnraLi5X0-2GyPD2dK70> @ladislav-nfa<https://url6.mailanyone.net/scanner?m=1pS1Gy-0000QT-4V&d=4%7Cmail%2F90%2F1676403600%2F1pS1Gy-0000QT-4V%7Cin6j%7C57e1b682%7C10717690%7C7962607%7C63EBE5506E134A1E3DA9F7CE5F804736&o=%2Fphti%3A%2Fgtsmbthlco%2Fu.-sadfavnila&s=uOdhcnDf2jGIzrIUq2dTGem1BHE> as we are now at the halfway mark of the workshop series, and making good progress on the ontology structure, I thought it could be a good moment to look at available vocabularies to incorporate into this project.

Below are a list of defined classes, and notes on where vocabularies are available, preferencing those which can be found in the Cataloguing Manual. I might begin adding these in directly and look forward to any discussion on which you think correspond with vocabularies used by institutions and which do not.

~

Work/Variant
Both manual and EN15907 agree on a vocabulary of four values (Analytic, Collection, Monographic, Serial) which @natashafairbairn<https://url6.mailanyone.net/scanner?m=1pS1Gy-0000QT-4V&d=4%7Cmail%2F90%2F1676403600%2F1pS1Gy-0000QT-4V%7Cin6j%7C57e1b682%7C10717690%7C7962607%7C63EBE5506E134A1E3DA9F7CE5F804736&o=%2Fphti%3A%2Fgtsmbthnco%2Fu.asatrafiahnriab&s=XSP4PTuq3-QulisZv3PtQoghKro> was keen to retain here.

Activity
The FIAF Glossary of Filmographic Terms contains a rich, multi-tier and multilingual vocabulary of terms (mostly under section "B").

Agent
The manual (1.4.1) lists a vocabulary of "Person", "Corporate Body", "Family" and "Person Group", but I wonder if this could be simplified to simply "Person" and "Organisation" as I have seen elsewhere? Although "Person Group" does address an ongoing problem where persons are credited in combination (eg "Coen Brothers", "The Wachowskis") and are not really a "person" nor an "organisation".

Person Group also needed for instances of music groups, which may be linked to Works as either cast or credits, or if Music Works database also exist in an institutions systems with links to Moving Image Works. We have “Person”, “Organisation” and “Group” designations on records in our names database (also Animal –  e.g. name record for Scruffy – a dog featuring in and credited as playing the role “Patsy the dog” in the 1937 film Storm in a Teacup – but let’s not complicate things)

Event
The manual (D.4) lists "Publication", "Award/Nomination", "Production", "Rights/Copyright/Registration", "Preservation", "Decision", "Manufacture", "Inspection" and "Acquisition". Each of these contain their own subclasses - my question here would be how these have been adopted by institutions, and whether we should support just the top level or the whole tree.

BFI uses Award/Nomination, Production (which is where locations information and production dates can be found), Publication (e.g. screenings at BFI Southbank cinemas*, Slots it has been transmitted in on television (UK television sometimes has themed day or week programmes under what it calls slots or seasons, e.g. Sci-Fi Weekend whereby various TV programmes and films with a science fiction theme are shown, often with a brief introductory programme beforehand). *technically speaking, and being purist, screenings would be associated with a Manifestation, but for us it was both easier to migrate legacy data to link to the Work and also better for users (both internal and external) who would be able to find all the information together in one place rather than scattered across multiple Manifestations of a Work.

With Manifestations we have also linked to BBFC classification (which I presume comes under “Registration”).

The other archive-related events such as Preservation, Inspection, Acquisition are all fields within Items rather than separate Events. We also have a separate Accessions database that Items can be linked to.

That is just the BFI though – other archives may have developed and used Events more.

Form
FIAF Glossary of Filmographic Terms contains a list of "Forms" under section "D".

Genre
No obvious resources come to mind, would be interesting to dedicate an upcoming talk to compare vocabularies between our institutions and see if there is convergence (or not!).

There is no one standard or list, most institutions follow their own or ones based on others, e.g. adapted Library of Congress ones, etc. but there will be some crossover/commonality of terms used, but I suspect possible subtle differences in definitions with some. A lot will depend on collections, user need,  and in some Forms and Genre can be together in the one list/field.

Identifier
The manual (1.3.1) lists ISAN, EIDR and VIAF. I would support adding Wikidata. There should also be support for internal identifiers here (eg BFI, NFA etc), but a technical question, how should these be modeled? It seems tedious to create "identifier" subclasses for each institutions. One approach is do more work on proper data provenance peer statement, and then just use an "internal identifier" class which can be used in combination with provenance data to derive source of identifier.

Subject
As a "subject" can be (to my understanding) virtually anything, hard to imagine a comprehensive vocabulary. Maybe the property can be kept open for any resource (eg Wikidata, LoC, etc).

Some archives may use other Library standards for Subjects as well, e.g. Dewey, UDC, etc. (For its Subject thesaurus construction and architecture the BFI utilises UDC terms and numbers, but adapted to our needs and requirements rather than straightforward replication, so uses a hybrid UDC-in-house basis

Title
The manual (A.2) lists "Alternative Title", "Identifying Title", "Other Title Information", "Preferred Title", "Supplied/Devised Title", "Title Proper". The manual also contains nine additional subclasses of "Alternative Title" (A.2.4.1). As with Event, is it useful to include the full set at this stage or just the top level?

Variant Type
The manual (D.2) contains the following vocabulary: "Censored", "Dubbed", "Subtitled", "Abridged/Condensed", "Augmented", "Preservation/Restoration"
"Different sound track", "Sonorized", "Colourized", "Black and white copy of work originally issued in colour".

Re. all the different terms/values featured in section D of the FIAF Moving Image Cataloguing – it is important to remember that these are purely examples and not full lists. As stated at the beginning of that Section: “The value lists provided in this appendix are usually limited to a minimum of five examples if more comprehensive lists are available. If no pre-existing and authoritative lists are available, a non-exhaustive but more comprehensive set of terms is provided.”

There is also the added footnote “It is recognised that vocabulary lists often require frequent updates, additions or amendments. For this reason, should resources permit, it would be ideal to separate value lists from the rules and locate them in a central, online repository, like metadataregistry.org. RDF-based repositories like this can supply up-to-date vocabularies on demand and have additional advantages over traditional value lists such as those found in this Appendix”. There were hopes to tie in with the FIAF glossaries of terms where possible.

Manifestation
The manual (D.5) contains a vocabulary: "Pre-Release", "Theatrical Distribution", "Non-Theatrical Distribution", "Not For Release", "Unreleased", "Home Viewing Publication", "Broadcast", "Internet", "Preservation/Restoration", "Unknown Manifestation".

Colour Characteristic
The manual (D.7.11) contains a vocabulary: "Colour", "Colour + Black & White", "Tinted", "Black and white", "Black and white (tinted)", "Black and white (toned)", "Black and white (tinted and toned)", "Sepia". My understanding is that the Colour Characteristic then has a "Has Colour Standard" property for technical specifics of the colour standards used, which has a vocabulary under D.7.12: "Pathécolor", "Technicolor", "Kinemacolor", "Anscocolor", "Ferraniacolor", "Fujicolor", "Kodachrome", "Eastmancolor", "RGB", "YUV".

Extent
The manual contains a vocabulary of Unit Types (D.7.6): "Reel", "Roll", "Cassette", "Cartridge", "Loop", "Disc", "File", "Digital tape". The manual 2.3.5.2 also recommends including "metres" and "feet", and digital measures like "MB", "GB" and "TB". 2.3.5.3 recommends the inclusion of duration, so "seconds", "minutes", "hours".

Format
The manual (D.7.2) contains a table of "specific carrier types" which could be nested under the "general carrier types" to serve as format vocabulary. This is clearly an incomplete list, but could serve as a good starting point.

Image Characteristic
The manual includes two vocabularies for Aspect Ratio (D.7.14) and Aperture Format (D.7.15). Aspect Ratios listed are: "2.34:1", "2.39:1", "2.52:1", "2.7:1", "4:3". I am wondering if the FIAF Projection Manual has a glossary which could also be used in this context? I feel like the Aperture vocabulary could be assessed critically as I feel it is maybe grouping a few different attributes together which are not siblings.

Language
The obvious resource here is ISO-639.

Language Usage
The manual (D.6) contains a vocabulary: "Dialogue language(s)", "Written languages", "Language(s) of summaries on containers", "Language(s) of accompanying material". Both "Dialogue" and "Written" have more granular entities.

Sound Characteristic
The manual (D.7.4) contains a vocabulary of sound types: "Sound", "Silent", "Mute", "Combined", "Combined as Mute", "Combined as Sound", "Mixed", "Temporary". It would be good to have clarification of the definition of some of these terms (eg "combined" as in "combined with image"?). Once the general nature of the sound has been declared there are additional properties for "Sound Configuration" (manual 3.1.5.4 suggests "mono" and "stereo") and "Sound system" which has a vocabulary under D.7.13: "Dolby SR", "Dolby Digital", "Mute", "Combined Magnetic Sound", "Combined Optical Sound", "VA RCA Duplex". There is also a vocabulary for "Sound Fixation" at D.7.5: "Needle sound", "Optical", "Magnetic", "Analogue sound", "Digital".

~

Item
As discussed in the Item discussion I was in favour of adopting D.7.8 from the manual as the item vocabulary: "Colour Positive", "Colour Negative", "Copper Toned Positive", "Cyan Matrix", "Direct BW Positive", "Original negative", "Duplicate negative", "Positive","Original positive (reversal film)", "Duplicate positive", "Lavender", "Image negative", "Sound negative", "DCP". However much of this is very film-specific, so it would possibly be better expressed as a separate property with "general carrier type" acting as "item type": "Film", "Video Tape", "Video Disc", "Digital Tape", "Digital Disc", "Digital File".

Base
The manual (D.7.7) contains a vocabulary of bases: "Acetate", "Acrylic", "CTA", "Diacetate", "Mainly safety", "Mainly nitrate", "Mixed", "Mylar", "Nitrate", "Polyester", "PVC", "Safety", "Video", "Vinyl".

Broadcast Standard
The manual (3.1.5.10) contains a vocabulary: "NTSC", "PAL", "SECAM".

Institution
A good suggestion from @Rose-EFG<https://url6.mailanyone.net/scanner?m=1pS1Gy-0000QT-4V&d=4%7Cmail%2F90%2F1676403600%2F1pS1Gy-0000QT-4V%7Cin6j%7C57e1b682%7C10717690%7C7962607%7C63EBE5506E134A1E3DA9F7CE5F804736&o=%2Fphti%3A%2FgtsmbthRco%2Fu.GFE-eso&s=F95t5J6V6joczeo4xowp1RrjBFg> is that there should be no "institution" class, instead institutions should be organisation "agents". FIAF itself holds a good vocabulary of member institutions.

Line Standard
The manual (D.7.21) contains a vocabulary: "405", "525", "625", "720", "1080"

Resolution
The manual (D.7.19) contains a vocabulary: "Standard Definition", "High Definition", "2k", "4k", "6k", "8k".

Source Device
The manual (D.7.20) contains a vocabulary: "DVSI", "VT20", "HDCAM SRW5500/2"

Source Software
No vocabulary in the manual, I would suggest "FFmpeg" and other transcoder/editors as a good start.

Status
The manual (D.7.3) contains a vocabulary: "Master", "Viewing", "Accessioned", "On Loan", "Status pending", "Removed".

Stock
The manual (D.7.16) contains an extensive vocabulary. As there is a lot of overlap between manufacturers (eg Fuji produced film and videotape, 3M video and audiotape) I would question whether these should be nested or flat. An additional property should be Stock Batch (or maybe "stock value", "stock specific"?) which contains a string of the exact stock (eg "Panchromatic Separation Film 2238").

Stream
This is the biggest diversion from the manual, and I would propose that a stream can be of type "Audio Stream", "Video Stream", "Subtitle Stream" (or "track"?). Additional properties are "Has Codec", which has vocabularies under D.7.10 in the manual which clearly need expansion. Also "Has Bit Depth", with a vocabulary present at D.7.17 of the manual.

Manual is weak on digital-related vocabularies and sections so would be good to get some vocabularies for those

Carrier
No vocabularies expressed.



—
Reply to this email directly, view it on GitHub<https://url6.mailanyone.net/scanner?m=1pS1Gy-0000QT-4V&d=4%7Cmail%2F90%2F1676403600%2F1pS1Gy-0000QT-4V%7Cin6j%7C57e1b682%7C10717690%7C7962607%7C63EBE5506E134A1E3DA9F7CE5F804736&o=%2Fphti%3A%2FgtsmbthFco%2Fu.e%2FIAlodlFmk-inhorsgwu%2Fopsssesi9%2F&s=Tkg8Ek2kotEnVpDt-jg7kdz0FHc>, or unsubscribe<https://url6.mailanyone.net/scanner?m=1pS1Gy-0000QT-4V&d=4%7Cmail%2F90%2F1676403600%2F1pS1Gy-0000QT-4V%7Cin6j%7C57e1b682%7C10717690%7C7962607%7C63EBE5506E134A1E3DA9F7CE5F804736&o=%2Fphti%3A%2Fgtsmbthnco%2Fu.tfotocaiiibunscsus%2Fnteri%2Fauhb-IAA566JRFZDHAYZTR36EMWF7APOVTXAFNCAM6ANS6UAAA7ITA3&s=llf3Km8l6yUfyYdzWz4_iuFDtEw>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>

The British Film Institute is governed by Royal Charter and is a charity registered in England and Wales number 287780. The contents of this e-mail are confidential and may be legally privileged. If you are not the intended recipient, kindly notify the sender that you have received this message in error and immediately delete it. Unless you are the intended recipient, you may not forward this e-mail to anybody, nor make any use of its contents.

**Comment by paulduchesne** [comment]
Thank you for these reponses @natashafairbairn, I have tried to format it below and will respond shortly. 

> Agent: The manual (1.4.1) lists a vocabulary of "Person", "Corporate Body", "Family" and "Person Group", but I wonder if this  could be simplified to simply "Person" and "Organisation" as I have seen elsewhere? Although "Person Group" does  address an ongoing problem where persons are credited in combination (eg "Coen Brothers", "The Wachowskis") and are not really a "person" nor an "organisation".

Person Group also needed for instances of music groups, which may be linked to Works as either cast or credits, or if Music Works database also exist in an institutions systems with links to Moving Image Works. We have “Person”, “Organisation” and “Group” designations on records in our names database (also Animal –  e.g. name record for Scruffy – a dog featuring in and credited as playing the role “Patsy the dog” in the 1937 film Storm in a Teacup – but let’s not complicate things)

> Event: The manual (D.4) lists "Publication", "Award/Nomination", "Production", "Rights/Copyright/Registration", "Preservation", "Decision", "Manufacture", "Inspection" and "Acquisition". Each of these contain their own subclasses - my question here would be how these have been adopted by institutions, and whether we should support just the top level or the whole tree.

BFI uses Award/Nomination, Production (which is where locations information and production dates can be found), Publication (e.g. screenings at BFI Southbank cinemas*, Slots it has been transmitted in on television (UK television sometimes has themed day or week programmes under what it calls slots or seasons, e.g. Sci-Fi Weekend whereby various TV programmes and films with a science fiction theme are shown, often with a brief introductory programme beforehand). 

*technically speaking, and being purist, screenings would be associated with a Manifestation, but for us it was both easier to migrate legacy data to link to the Work and also better for users (both internal and external) who would be able to find all the information together in one place rather than scattered across multiple Manifestations of a Work.

With Manifestations we have also linked to BBFC classification (which I presume comes under “Registration”).

The other archive-related events such as Preservation, Inspection, Acquisition are all fields within Items rather than separate Events. We also have a separate Accessions database that Items can be linked to.

That is just the BFI though – other archives may have developed and used Events more.

> Genre: No obvious resources come to mind, would be interesting to dedicate an upcoming talk to compare vocabularies between our institutions and see if there is convergence (or not!).

There is no one standard or list, most institutions follow their own or ones based on others, e.g. adapted Library of Congress ones, etc. but there will be some crossover/commonality of terms used, but I suspect possible subtle differences in definitions with some. A lot will depend on collections, user need,  and in some Forms and Genre can be together in the one list/field.

> Subject: As a "subject" can be (to my understanding) virtually anything, hard to imagine a comprehensive vocabulary. Maybe the property can be kept open for any resource (eg Wikidata, LoC, etc).

Some archives may use other Library standards for Subjects as well, e.g. Dewey, UDC, etc. (For its Subject thesaurus construction and architecture the BFI utilises UDC terms and numbers, but adapted to our needs and requirements rather than straightforward replication, so uses a hybrid UDC-in-house basis

> Variant Type: The manual (D.2) contains the following vocabulary: "Censored", "Dubbed", "Subtitled", "Abridged/Condensed", "Augmented", "Preservation/Restoration"
"Different sound track", "Sonorized", "Colourized", "Black and white copy of work originally issued in colour".

Re. all the different terms/values featured in section D of the FIAF Moving Image Cataloguing – it is important to remember that these are purely examples and not full lists. As stated at the beginning of that Section: “The value lists provided in this appendix are usually limited to a minimum of five examples if more comprehensive lists are available. If no pre-existing and authoritative lists are available, a non-exhaustive but more comprehensive set of terms is provided.”

There is also the added footnote “It is recognised that vocabulary lists often require frequent updates, additions or amendments. For this reason, should resources permit, it would be ideal to separate value lists from the rules and locate them in a central, online repository, like metadataregistry.org. RDF-based repositories like this can supply up-to-date vocabularies on demand and have additional advantages over traditional value lists such as those found in this Appendix”. There were hopes to tie in with the FIAF glossaries of terms where possible.

**Comment by paulduchesne** [comment]
> Person Group also needed for instances of music groups, which may be linked to Works as either cast or credits, or if Music Works database also exist in an institutions systems with links to Moving Image Works. We have “Person”, “Organisation” and “Group” designations on records in our names database (also Animal – e.g. name record for Scruffy – a dog featuring in and credited as playing the role “Patsy the dog” in the 1937 film Storm in a Teacup – but let’s not complicate things)

Thank you for the clarification. Can I ask about "family", is this meant as a literal family? Another concern was that "Corporate Body" would not include informal, non-corporate organisations (eg artist collectives, musical groups) so it makes sense that "Person Group" can cover those entities.

> BFI uses Award/Nomination, Production (which is where locations information and production dates can be found), Publication (e.g. screenings at BFI Southbank cinemas*...

Could I ask if you also use the event vocabularies (for example the "D.11 Production Event Types")? As mentioned I realise there is a bit of overlap between the Manifestation type (going with our current definition, often linked closely to a discrete event) and the event itself.  

> Re. all the different terms/values featured in section D of the FIAF Moving Image Cataloguing – it is important to remember that these are purely examples and not full lists. 

I see this as being a key strategic question for moving forward. My initial thought was that the first iteration should be without vocabularies, but I am now thinking that maybe a good way forward is to use these example vocabularies as a starting point, take them out into the world and inevitably iterate, and developments could also maybe be fed back into the glossaries/manual.

**Comment by natashafairbairn** [comment]
Hi Paul,

Answers to your further questions within your email below.

Best,
Natasha

**Comment by ladislav-nfa** [comment]
This is our [proposal](https://docs.google.com/spreadsheets/d/18TM6WeN-TpNXURhx2znSOeLb_iIASLB1uH91hXupJVc/edit#gid=1896922276) for controlled vocabularies lists for our new system (just for some elements). The Item Element typology is perhaps the only elaborated CV of all in the table.
Any comments to Item Element typology or other parts will be of course highly appreciated.

**Comment by ladislav-nfa** [comment]
And there are controlled vocabularies in our current old cataloguing system [here.](https://docs.google.com/spreadsheets/d/1f80TRGSp2wLulBddvM4cAL9WVr2XYwRCqyOxsDxkGG4/edit?usp=sharing)
(slightly inconsistent as you can see - due to 30 years of extending it in very old software in COBOL.)

**Comment by paulduchesne** [comment]
All cataloguing manual (and iso) vocabularies have now been added, so I will close this ticket.
